[build-system]
requires = ["setuptools>=75"]
build-backend = "setuptools.build_meta"

[project]
name = "lost-found-api"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "asyncpg==0.30.0",
  "fastapi==0.116.1",
  "pydantic-settings==2.10.1",
  "sqlalchemy[asyncio]==2.0.41",
]

[project.optional-dependencies]
dev = ["httpx==0.28.1", "pytest==8.4.1", "pytest-asyncio==1.1.0"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-ra"

[tool.setuptools.packages.find]
where = ["."]
include = ["app*"]
